# Generated by Django 3.2.6 on 2021-10-14 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_alter_input_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='input',
            old_name='image',
            new_name='title',
        ),
    ]
